# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: The Mojo Programming Language
author: Amit Shukla
logo: logo.png

# Force-execute notebooks on each build (set to "off" to skip)
execute:
  execute_notebooks: "off"

# Name of the LaTeX output file for PDF builds
latex:
  latex_documents:
    targetname: the-mojo-book.tex

# Bibtex file for citations
bibtex_bibfiles:
  - references.bib

# Where the book lives on the web
repository:
  url: https://github.com/AmitXShukla/Mojo
  path_to_book: book-src
  branch: main

# GitHub buttons
html:
  use_issues_button: true
  use_repository_button: true
